Enhancement/improve docs for v0.0.9
CrossMint/crossmint-client-sdk pull request #45
Opened 2022-02-23 20:03 UTC by pgarciaegido

Hey,

Just improving the docs for our release soon. I have a lot of fields on TBD, Ill research each of them and try to come up with a good description shortly. But if you guys want to chip in, feel free 😄

2022-02-23 20:13 UTC, alfonso-paella requested changes

2022-02-23 20:13 UTC, alfonso-paella commented on README.md
> +-   Ethereum L1 (end of Feb 2021)
March 2021

2022-02-23 20:13 UTC, alfonso-paella commented on README.md
> +# REPLACE
Not sure if this is a placeholder? I guess it is

2022-02-23 20:13 UTC, alfonso-paella commented on README.md
> +Just import the the Pay with `CrossMintButton` into your app wherever you would like. It's that simple!
Let's add back a point to ensure they test that the button shows up if a user doesn't have a crypto wallet like Phantom. A lot of ppl make this mistake where they put it in a place where it's not visible unless you have a wallet connected

2022-02-23 20:13 UTC, alfonso-paella commented on packages/ui/react-ui/README.md
> +| mintTo                   | `undefined` | `false`  | TBD                                                                                          |
I would leave out (undocumented) all the ones you listed as TBD, as some / most of them for now are for special partner integrations only

2022-02-23 20:13 UTC, pgarciaegido commented on README.md
> +# REPLACE
I have added this as a reminder to myself to replace the old gif with a new one. Will do that shortly.

2022-02-23 22:12 UTC, pgarciaegido commented on README.md
> +# REPLACE
Actually, maybe its better to take care of it later and have a little discussion on what to show in the gif, (or if we even want a gif there)

2022-02-24 05:32 UTC, alfonso-paella approved these changes

2022-02-24 07:40 UTC, merged