Adding web component UI button
Crossmint/crossmint-client-sdk pull request #77
Opened 2022-03-23 17:11 UTC by pgarciaegido

Adding a crossmint button using web components for vanilla apps.

The funny thing is that this actually works everywhere (vue, react...) Actually tested it in the react starter.

Promising!

This only covers CrossmintPayButton. Lots of stuff to polish yet here.

Also CrossmingStatusButton is still missing.

2022-03-25 16:06 UTC, pgarciaegido commented on packages/ui/vanilla-ui/src/CrossmintPayButton.ts
> +    @property({ type: String })
So this is the only think that in my opinion needs to improve: we need to be able to somehow reference our button interface so if we add like a new property out of the interface the build will break. I opened a new issue on stack overflow. https://stackoverflow.com/questions/71618356/how-do-i-make-sure-that-my-lit-element-component-props-are-properly-typed-in-typ in case you want to upvote it.

2022-03-25 16:07 UTC, pgarciaegido commented
So everything seems to be working fine with the Pay button. Next steps:
- Status button
- Documentation
- Maybe an starter? Altought we can use whatever starter we want to test

2022-03-27 03:36 UTC, pgarciaegido commented
@mPaella this is ready to be reviewed... unfortunately the PR got like crazy big, had to do changes on the base aswell... 

Lemme know if it looks OK to you 😄

2022-03-27 04:29 UTC, alfonso-paella requested changes

2022-03-27 04:29 UTC, alfonso-paella commented on packages/ui/vanilla-ui/package.json
> +  "homepage": "https://github.com/CrossMint/crossmint-client-sdk#readme",
Crossmint (lowercase M)

2022-03-27 04:29 UTC, alfonso-paella commented on packages/ui/vanilla-ui/package.json
> +  "description": "Vanilla Crossmint button using web-components",
Crossmint client SDK for vanilla JS (no framework required), using web-components

2022-03-27 04:29 UTC, alfonso-paella commented on packages/ui/vanilla-ui/package.json
> +  "author": "Paella Labs Inc",
Paella Inc

2022-03-27 04:29 UTC, alfonso-paella commented on packages/ui/vanilla-ui/package.json
> +  "dependencies": {
could some of these be devDependencies?

2022-03-29 17:51 UTC, mPaella approved these changes
LGTM

2022-03-29 18:41 UTC, merged